<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_infokatalon.com_fa fa-facebook fa-fw fa-3x (1)</name>
   <tag></tag>
   <elementGuidId>0811d9b9-2700-44fe-831f-cdb0eeced443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-facebook.fa-fw.fa-3x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4361c6af-9366-49fd-97c3-0c7ed322bbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-facebook fa-fw fa-3x</value>
      <webElementGuid>d3074fa9-343c-4756-b096-91a5d153db06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-10 col-lg-offset-1 text-center&quot;]/ul[@class=&quot;list-inline&quot;]/li[1]/a[1]/i[@class=&quot;fa fa-facebook fa-fw fa-3x&quot;]</value>
      <webElementGuid>bcf32ca6-37ad-4aa6-a1fd-58b11f12eebd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/i</value>
      <webElementGuid>c08526a8-fd7d-4790-898b-8f0b4ed21669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
